name: vip_chat_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_button: ^0.0.4
  animated_text_kit: ^3.1.2
  font_awesome_flutter: ^8.11.0
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_storage: ^8.0.3
  cloud_firestore: ^1.0.0
  flutter_login_facebook: ^1.0.1
  flutter_facebook_login_web: ^0.2.1+1
  modal_progress_hud: ^0.1.3
  keyboard_dismisser: ^2.0.0
  animated_drawer: ^0.0.4
  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:
  - family: Gruppo
    fonts:
    - asset: fonts/Gruppo-Regular.ttf

  - family: FingerPaint
    fonts:
    - asset: fonts/FingerPaint-Regular.ttf

  - family: BungeeShade
    fonts:
    - asset: fonts/BungeeShade-Regular.ttf

  - family: SourceSansPro
    fonts:
    - asset: fonts/SourceSansPro-Regular.ttf
    - asset: fonts/SourceSansPro-SemiBold.ttf
    - asset: fonts/SourceSansPro-Bold.ttf
